# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-14 16:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('linkageApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdonorlinkage',
            name='comment',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='patientdonorlinkage',
            name='date_completed',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patientdonorlinkage',
            name='donor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donor', to='linkageApp.DonorOrganization'),
        ),
        migrations.AlterField(
            model_name='patientdonorlinkage',
            name='exit_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='linkageApp.ExitStatus'),
        ),
        migrations.AlterField(
            model_name='patientdonorlinkage',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='linkage_status', to='linkageApp.LinkageStatus'),
        ),
    ]
